// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSkdniquEQA0PonS8qlIQZp9SSOpPvwck',
    appId: '1:950645223660:web:87dfe5bffb62d9a1a0b5c9',
    messagingSenderId: '950645223660',
    projectId: 'calorie-ai-2cbb0',
    authDomain: 'calorie-ai-2cbb0.firebaseapp.com',
    storageBucket: 'calorie-ai-2cbb0.firebasestorage.app',
    measurementId: 'G-NDQKWJXTSW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCd7ujYg_75XV-lFg6jDXFTfZ3MtfZZ9rA',
    appId: '1:950645223660:android:cd4fba9f1c0f6da4a0b5c9',
    messagingSenderId: '950645223660',
    projectId: 'calorie-ai-2cbb0',
    storageBucket: 'calorie-ai-2cbb0.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDM3eMJNwR1bzMs_LzbFyN3RD7pBCEDpos',
    appId: '1:950645223660:ios:e3d45bb3682ec84da0b5c9',
    messagingSenderId: '950645223660',
    projectId: 'calorie-ai-2cbb0',
    storageBucket: 'calorie-ai-2cbb0.firebasestorage.app',
    androidClientId: '950645223660-69a39c6t27p4sfp69teq20ve8buphpgj.apps.googleusercontent.com',
    iosClientId: '950645223660-1h4p4m2amvl8hhra99v69aipac9uon9h.apps.googleusercontent.com',
    iosBundleId: 'com.srhsoftwares.mycaloriepal',
  );
}
